name: Build Android APK

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        
    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
        
    - name: Setup Java JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
      
    - name: Clean npm cache and install dependencies
      run: |
        npm cache clean --force
        rm -rf node_modules package-lock.json
        npm install
      
    - name: Build web application
      run: npm run build
      
    - name: Create index.html for Capacitor
      run: |
        # Ensure the output directory exists
        mkdir -p .output/public
        
        # Create index.html file that Capacitor needs
        cat > .output/public/index.html << 'EOF'
        <!DOCTYPE html>
        <html lang="en">
        <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <meta name="apple-mobile-web-app-capable" content="yes">
            <meta name="apple-mobile-web-app-status-bar-style" content="default">
            <title>UPCR Mobile</title>
            <link rel="stylesheet" href="/_build/assets/client.css">
        </head>
        <body>
            <div id="root">
                <div style="display: flex; justify-content: center; align-items: center; height: 100vh; font-family: system-ui;">
                    <div style="text-align: center;">
                        <div style="margin-bottom: 20px; font-size: 24px;">UPCR Mobile</div>
                        <div>Loading...</div>
                    </div>
                </div>
            </div>
            <script type="module" src="/_build/assets/client.js"></script>
        </body>
        </html>
        EOF
        
        # Verify the file was created and show directory contents
        echo "📁 Contents of .output/public:"
        ls -la .output/public/
        echo "✅ index.html created successfully"
        
    - name: Install Capacitor CLI globally
      run: npm install -g @capacitor/cli@latest
      
    - name: Remove existing android directory
      run: rm -rf android
      
    - name: Add Android platform
      run: npx cap add android
      
    - name: Sync Capacitor
      run: npx cap sync android
      
    - name: Verify Android project structure
      run: |
        echo "📁 Android project structure:"
        ls -la android/
        echo "📱 App directory:"
        ls -la android/app/
        
    - name: Make gradlew executable
      run: chmod +x android/gradlew
      
    - name: Clean Android build
      run: |
        cd android
        ./gradlew clean --no-daemon
        
    - name: Build Android APK (Debug)
      run: |
        cd android
        ./gradlew assembleDebug --no-daemon --stacktrace --info
        
    - name: Verify APK was created
      run: |
        echo "🔍 Looking for APK files:"
        find android/ -name "*.apk" -type f
        ls -la android/app/build/outputs/apk/debug/ || echo "❌ Debug APK directory not found"
        
    - name: Upload APK artifact
      if: success()
      uses: actions/upload-artifact@v4
      with:
        name: upcr-mobile-debug-apk
        path: android/app/build/outputs/apk/debug/app-debug.apk
        retention-days: 30
        
    - name: Upload full build output (for debugging)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: build-debug-files
        path: |
          android/app/build/outputs/logs/
          android/app/build/reports/
          android/build.gradle
          android/app/build.gradle
          capacitor.config.ts
          package.json
        retention-days: 7 